[package]
name = "grl5_a_diameter_of_tree"
version = "0.1.0"
authors = ["hanare <hanare08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
